In [2]:
pip install -U langchain-ollama

Collecting langchain-ollama
  Downloading langchain_ollama-0.1.1-py3-none-any.whl (12 kB)
Collecting langchain-core<0.3.0,>=0.2.20 (from langchain-ollama)
  Downloading langchain_core-0.2.35-py3-none-any.whl (394 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.9/394.9 kB 4.3 MB/s eta 0:00:00a 0:00:01
Collecting ollama<1,>=0.3.0 (from langchain-ollama)
  Downloading ollama-0.3.1-py3-none-any.whl (10 kB)
Requirement already satisfied: PyYAML>=5.3 in ./miniconda3/lib/python3.11/site-packages (from langchain-core<0.3.0,>=0.2.20->langchain-ollama) (6.0)
Collecting jsonpatch<2.0,>=1.33 (from langchain-core<0.3.0,>=0.2.20->langchain-ollama)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Collecting langsmith<0.2.0,>=0.1.75 (from langchain-core<0.3.0,>=0.2.20->langchain-ollama)
  Downloading langsmith-0.1.104-py3-none-any.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.1/149.1 kB 19.3 MB/s eta 0:00:00
Collecting packaging<25,>=23.2 (from langchain-core<0.3.0,>=0.2.20->langchain-ollama)
  Using cached packaging-24.1-py3-none-any.whl (53 kB)
Requirement already satisfied: pydantic<3,>=1 in ./miniconda3/lib/python3.11/site-packages (from langchain-core<0.3.0,>=0.2.20->langchain-ollama) (2.8.2)
Collecting tenacity!=8.4.0,<9.0.0,>=8.1.0 (from langchain-core<0.3.0,>=0.2.20->langchain-ollama)
  Downloading tenacity-8.5.0-py3-none-any.whl (28 kB)
Requirement already satisfied: typing-extensions>=4.7 in ./miniconda3/lib/python3.11/site-packages (from langchain-core<0.3.0,>=0.2.20->langchain-ollama) (4.12.2)
Requirement already satisfied: httpx<0.28.0,>=0.27.0 in ./miniconda3/lib/python3.11/site-packages (from ollama<1,>=0.3.0->langchain-ollama) (0.27.0)
Requirement already satisfied: anyio in ./miniconda3/lib/python3.11/site-packages (from httpx<0.28.0,>=0.27.0->ollama<1,>=0.3.0->langchain-ollama) (4.4.0)
Requirement already satisfied: certifi in ./miniconda3/lib/python3.11/site-packages (from httpx<0.28.0,>=0.27.0->ollama<1,>=0.3.0->langchain-ollama) (2023.7.22)
Requirement already satisfied: httpcore==1.* in ./miniconda3/lib/python3.11/site-packages (from httpx<0.28.0,>=0.27.0->ollama<1,>=0.3.0->langchain-ollama) (1.0.5)
Requirement already satisfied: idna in ./miniconda3/lib/python3.11/site-packages (from httpx<0.28.0,>=0.27.0->ollama<1,>=0.3.0->langchain-ollama) (3.4)
Requirement already satisfied: sniffio in ./miniconda3/lib/python3.11/site-packages (from httpx<0.28.0,>=0.27.0->ollama<1,>=0.3.0->langchain-ollama) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in ./miniconda3/lib/python3.11/site-packages (from httpcore==1.*->httpx<0.28.0,>=0.27.0->ollama<1,>=0.3.0->langchain-ollama) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in ./miniconda3/lib/python3.11/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.20->langchain-ollama) (2.1)
Collecting orjson<4.0.0,>=3.9.14 (from langsmith<0.2.0,>=0.1.75->langchain-core<0.3.0,>=0.2.20->langchain-ollama)
  Downloading orjson-3.10.7-cp311-cp311-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl (251 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.3/251.3 kB 12.7 MB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2 in ./miniconda3/lib/python3.11/site-packages (from langsmith<0.2.0,>=0.1.75->langchain-core<0.3.0,>=0.2.20->langchain-ollama) (2.32.3)
Requirement already satisfied: annotated-types>=0.4.0 in ./miniconda3/lib/python3.11/site-packages (from pydantic<3,>=1->langchain-core<0.3.0,>=0.2.20->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in ./miniconda3/lib/python3.11/site-packages (from pydantic<3,>=1->langchain-core<0.3.0,>=0.2.20->langchain-ollama) (2.20.1)
Requirement already satisfied: charset-normalizer<4,>=2 in ./miniconda3/lib/python3.11/site-packages (from requests<3,>=2->langsmith<0.2.0,>=0.1.75->langchain-core<0.3.0,>=0.2.20->langchain-ollama) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./miniconda3/lib/python3.11/site-packages (from requests<3,>=2->langsmith<0.2.0,>=0.1.75->langchain-core<0.3.0,>=0.2.20->langchain-ollama) (1.26.16)
Installing collected packages: tenacity, packaging, orjson, jsonpatch, ollama, langsmith, langchain-core, langchain-ollama
  Attempting uninstall: packaging
    Found existing installation: packaging 23.0
    Uninstalling packaging-23.0:
      Successfully uninstalled packaging-23.0
  Attempting uninstall: jsonpatch
    Found existing installation: jsonpatch 1.32
    Uninstalling jsonpatch-1.32:
      Successfully uninstalled jsonpatch-1.32
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.4.3 requires pyqt5<5.16, which is not installed.
spyder 5.4.3 requires pyqtwebengine<5.16, which is not installed.
python-lsp-black 1.2.1 requires black>=22.3.0, but you have black 0.0 which is incompatible.
Successfully installed jsonpatch-1.33 langchain-core-0.2.35 langchain-ollama-0.1.1 langsmith-0.1.104 ollama-0.3.1 orjson-3.10.7 packaging-24.1 tenacity-8.5.0
Note: you may need to restart the kernel to use updated packages.

In [35]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_ollama.llms import OllamaLLM

In [36]:
llm = OllamaLLM(model="llama3")

In [37]:

import pandas as pd
df = pd.read_csv("Student grades - grades.csv")
df

       Student  Math_Grade  Physics_Grade
0    Student_1          88             84
1    Student_2          78             82
2    Student_3          64             65
3    Student_4          92             88
4    Student_5          57             51
5    Student_6          70             69
6    Student_7          88             85
7    Student_8          68             67
8    Student_9          72             70
9   Student_10          60             61
10  Student_11          60             53
11  Student_12          73             78
12  Student_13          85             98
13  Student_14          89             94
14  Student_15          73             74
15  Student_16          52             56
16  Student_17          71             65
17  Student_18          51             43
18  Student_19          73             76
19  Student_20          93             90
20  Student_21          79             72
21  Student_22          87             82
22  Student_23          51             45
23  Student_24          70             70
24  Student_25          82             84
25  Student_26          61             65
26  Student_27          71             75
27  Student_28          93             96
28  Student_29          74             72
29  Student_30          98             94
30  Student_31          76             68
31  Student_32          91             96
32  Student_33          77             76
33  Student_34          65             62
34  Student_35          64             69
35  Student_36          96             91
36  Student_37          93             97
37  Student_38          52             53
38  Student_39          86             80
39  Student_40          56             55

In [15]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.2-cp311-cp311-macosx_11_0_arm64.whl (11.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 21.4 MB/s eta 0:00:0000:0100:01
Collecting numpy>=1.23.2 (from pandas)
  Downloading numpy-2.1.0-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 26.3 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./miniconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 30.9 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in ./miniconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.1.0 pandas-2.2.2 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [38]:
import pandas as pd
df = pd.read_csv("Student grades - grades.csv")
df

       Student  Math_Grade  Physics_Grade
0    Student_1          88             84
1    Student_2          78             82
2    Student_3          64             65
3    Student_4          92             88
4    Student_5          57             51
5    Student_6          70             69
6    Student_7          88             85
7    Student_8          68             67
8    Student_9          72             70
9   Student_10          60             61
10  Student_11          60             53
11  Student_12          73             78
12  Student_13          85             98
13  Student_14          89             94
14  Student_15          73             74
15  Student_16          52             56
16  Student_17          71             65
17  Student_18          51             43
18  Student_19          73             76
19  Student_20          93             90
20  Student_21          79             72
21  Student_22          87             82
22  Student_23          51             45
23  Student_24          70             70
24  Student_25          82             84
25  Student_26          61             65
26  Student_27          71             75
27  Student_28          93             96
28  Student_29          74             72
29  Student_30          98             94
30  Student_31          76             68
31  Student_32          91             96
32  Student_33          77             76
33  Student_34          65             62
34  Student_35          64             69
35  Student_36          96             91
36  Student_37          93             97
37  Student_38          52             53
38  Student_39          86             80
39  Student_40          56             55

In [39]:
total_rows = len(df)
# Get index list
def hop(start, stop, step):
    for i in range(start, stop, step):
        yield i
    yield stop

index_list = list(hop(0,total_rows, 30))
index_list

[0, 30, 40]

In [19]:
pip install plotly panel

Collecting plotly
  Downloading plotly-5.23.0-py3-none-any.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 21.2 MB/s eta 0:00:0000:0100:01
Collecting panel
  Downloading panel-1.4.5-py3-none-any.whl (24.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.7/24.7 MB 10.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: tenacity>=6.2.0 in ./miniconda3/lib/python3.11/site-packages (from plotly) (8.5.0)
Requirement already satisfied: packaging in ./miniconda3/lib/python3.11/site-packages (from plotly) (24.1)
Collecting bokeh<3.5.0,>=3.4.0 (from panel)
  Downloading bokeh-3.4.3-py3-none-any.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 14.4 MB/s eta 0:00:0000:0100:01
Collecting param<3.0,>=2.1.0 (from panel)
  Downloading param-2.1.1-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.8/116.8 kB 16.4 MB/s eta 0:00:00
Collecting pyviz-comms>=2.0.0 (from panel)
  Downloading pyviz_comms-3.0.3-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 11.3 MB/s eta 0:00:00
Collecting xyzservices>=2021.09.1 (from panel)
  Downloading xyzservices-2024.6.0-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.9/83.9 kB 11.3 MB/s eta 0:00:00
Collecting markdown (from panel)
  Downloading Markdown-3.7-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 15.2 MB/s eta 0:00:00
Requirement already satisfied: markdown-it-py in ./miniconda3/lib/python3.11/site-packages (from panel) (3.0.0)
Requirement already satisfied: linkify-it-py in ./miniconda3/lib/python3.11/site-packages (from panel) (2.0.3)
Requirement already satisfied: mdit-py-plugins in ./miniconda3/lib/python3.11/site-packages (from panel) (0.4.1)
Requirement already satisfied: requests in ./miniconda3/lib/python3.11/site-packages (from panel) (2.32.3)
Requirement already satisfied: tqdm>=4.48.0 in ./miniconda3/lib/python3.11/site-packages (from panel) (4.65.0)
Requirement already satisfied: bleach in ./miniconda3/lib/python3.11/site-packages (from panel) (4.1.0)
Requirement already satisfied: typing-extensions in ./miniconda3/lib/python3.11/site-packages (from panel) (4.12.2)
Requirement already satisfied: pandas>=1.2 in ./miniconda3/lib/python3.11/site-packages (from panel) (2.2.2)
Requirement already satisfied: Jinja2>=2.9 in ./miniconda3/lib/python3.11/site-packages (from bokeh<3.5.0,>=3.4.0->panel) (3.1.2)
Collecting contourpy>=1.2 (from bokeh<3.5.0,>=3.4.0->panel)
  Downloading contourpy-1.2.1-cp311-cp311-macosx_11_0_arm64.whl (245 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.9/245.9 kB 16.2 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.16 in ./miniconda3/lib/python3.11/site-packages (from bokeh<3.5.0,>=3.4.0->panel) (2.1.0)
Collecting pillow>=7.1.0 (from bokeh<3.5.0,>=3.4.0->panel)
  Downloading pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 25.2 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: PyYAML>=3.10 in ./miniconda3/lib/python3.11/site-packages (from bokeh<3.5.0,>=3.4.0->panel) (6.0)
Requirement already satisfied: tornado>=6.2 in ./miniconda3/lib/python3.11/site-packages (from bokeh<3.5.0,>=3.4.0->panel) (6.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/lib/python3.11/site-packages (from pandas>=1.2->panel) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./miniconda3/lib/python3.11/site-packages (from pandas>=1.2->panel) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in ./miniconda3/lib/python3.11/site-packages (from pandas>=1.2->panel) (2024.1)
Requirement already satisfied: six>=1.9.0 in ./miniconda3/lib/python3.11/site-packages (from bleach->panel) (1.16.0)
Requirement already satisfied: webencodings in ./miniconda3/lib/python3.11/site-packages (from bleach->panel) (0.5.1)
Requirement already satisfied: uc-micro-py in ./miniconda3/lib/python3.11/site-packages (from linkify-it-py->panel) (1.0.3)
Requirement already satisfied: mdurl~=0.1 in ./miniconda3/lib/python3.11/site-packages (from markdown-it-py->panel) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./miniconda3/lib/python3.11/site-packages (from requests->panel) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/lib/python3.11/site-packages (from requests->panel) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./miniconda3/lib/python3.11/site-packages (from requests->panel) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in ./miniconda3/lib/python3.11/site-packages (from requests->panel) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.0 in ./miniconda3/lib/python3.11/site-packages (from Jinja2>=2.9->bokeh<3.5.0,>=3.4.0->panel) (2.1.1)
Installing collected packages: xyzservices, plotly, pillow, param, markdown, contourpy, pyviz-comms, bokeh, panel
Successfully installed bokeh-3.4.3 contourpy-1.2.1 markdown-3.7 panel-1.4.5 param-2.1.1 pillow-10.4.0 plotly-5.23.0 pyviz-comms-3.0.3 xyzservices-2024.6.0
Note: you may need to restart the kernel to use updated packages.

In [40]:
prompt = f"""
**Function:** analyze_data
The data below contains student grades in Math and Physics.
* Calculate the correlation coefficient between Math and Physics grades.
* Interpret the strength and direction of the correlation (positive or negative).
* Summarize any insights you can glean from the correlation analysis.
Data: {data}
"""

In [41]:
# Extract math and physics grades
math_grades = df["Math_Grade"].tolist()
physics_grades = df["Physics_Grade"].tolist()

In [42]:
# Prepare data for analysis
data = {
    "math_grades": math_grades,
    "physics_grades": physics_grades
}

# Create analysis prompt
prompt = f"""
**Function:** analyze_grades

The data below contains student grades in Math and Physics for 40 students.
Please provide a simple analysis of this data, including:
1. The average grade for each subject
2. The highest and lowest grades for each subject
3. A brief comparison of performance between Math and Physics
4. correlation between maths and physics grades.

Data: {data}
"""

In [44]:
# output = llm.invoke(prompt)
print(output)

    Analysis of Math and Physics Grades:
    1. Math Grade Statistics:
       - Average grade: 74.47
       - Highest grade: 98
       - Lowest grade: 51

    2. Physics Grade Statistics:
       - Average grade: 73.78
       - Highest grade: 98
       - Lowest grade: 43

    3. Comparison:
       The average grade in Math (74.47) is higher than the average grade in Physics (73.78).
       Physics has the highest individual grade.
       Math has the higher lowest grade.

    This simple analysis provides a basic overview of student performance in Math and Physics, highlighting the average, highest, and lowest grades for each subject.

In [45]:
prompt = f"""
The data below contains student grades in Math and Physics. 
* Calculate the correlation coefficient between Math and Physics grades.
* Interpret the strength and direction of the correlation (positive or negative).
* Summarize the findings based on the correlation analysis.

Data: {data}
"""

In [46]:
print(output)

    Analysis of Math and Physics Grades:
    1. Math Grade Statistics:
       - Average grade: 74.47
       - Highest grade: 98
       - Lowest grade: 51

    2. Physics Grade Statistics:
       - Average grade: 73.78
       - Highest grade: 98
       - Lowest grade: 43

    3. Comparison:
       The average grade in Math (74.47) is higher than the average grade in Physics (73.78).
       Physics has the highest individual grade.
       Math has the higher lowest grade.

    This simple analysis provides a basic overview of student performance in Math and Physics, highlighting the average, highest, and lowest grades for each subject.

In [47]:
llm.invoke("The first man on the moon was...")

'A classic question!\n\nThe answer is: Neil Armstrong. On July 20, 1969, NASA\'s Apollo 11 mission successfully landed two astronauts, Neil Armstrong and Edwin "Buzz" Aldrin, on the surface of the Moon. Armstrong became the first person to set foot on the Moon at 2:56 UTC on July 21, famously declaring, "That\'s one small step for man, one giant leap for mankind."'

In [48]:
# Create analysis prompt 1
prompt = f"""
**Function:** analyze_grades

The data below contains student grades in Math and Physics for 40 students.
Please provide a simple analysis of this data, including:
1. The average grade for each subject
2. The highest and lowest grades for each subject
3. A brief comparison of performance between Math and Physics

Data: {data}
"""

In [49]:
output = llm.invoke(prompt)
print(output)

Here is the analysis of the grades:

**Average Grade for Each Subject:**

* Math: (sum of math grades) / 40 = 74.75
* Physics: (sum of physics grades) / 40 = 73.15

**Highest and Lowest Grades for Each Subject:**

* Math:
	+ Highest: 98
	+ Lowest: 51
* Physics:
	+ Highest: 98
	+ Lowest: 43

**Comparison of Performance between Math and Physics:**

The average grade in Math is slightly higher than in Physics. However, both subjects have a similar range of highest and lowest grades. The highest grade in both subjects is the same (98), but the lowest grade in Math is 51, while in Physics it's 43. This suggests that students may be more consistent in their performance in Math compared to Physics.

Overall, the analysis shows that the majority of students performed well in both subjects, with average grades above 70%. However, there are a few students who struggled, particularly in Physics where some students scored as low as 43.

In [50]:
# Prompt 2: Grade Distribution
prompt_grade_distribution = f"""
**Function:** analyze_grade_distribution

The data below contains student grades in Math and Physics for 40 students.
Please analyze the grade distribution for each subject:
1. How many students scored 90 or above?
2. How many students scored between 80 and 89?
3. How many students scored between 70 and 79?
4. How many students scored between 60 and 69?
5. How many students scored below 60?

Provide this information for both Math and Physics.

Data: {data}
"""
output = llm.invoke(prompt_grade_distribution)
print(output)

Let's analyze the grade distribution for both Math and Physics.

**Math**

1. How many students scored 90 or above?
Answer: 6 (92, 93, 98, 96, 93, 91)
2. How many students scored between 80 and 89?
Answer: 7 (88, 87, 85, 89, 86, 82, 85)
3. How many students scored between 70 and 79?
Answer: 4 (78, 77, 76, 73)
4. How many students scored between 60 and 69?
Answer: 5 (68, 67, 65, 64, 61)
5. How many students scored below 60?
Answer: 14 (57, 56, 52, 51, 53, 43, 45, 55)

**Physics**

1. How many students scored 90 or above?
Answer: 6 (98, 94, 96, 95, 94, 91)
2. How many students scored between 80 and 89?
Answer: 7 (88, 85, 84, 82, 81, 80, 83)
3. How many students scored between 70 and 79?
Answer: 4 (78, 76, 75, 74)
4. How many students scored between 60 and 69?
Answer: 5 (69, 67, 65, 64, 62)
5. How many students scored below 60?
Answer: 14 (53, 51, 45, 43, 55)

Let me know if you have any further questions!

In [52]:
# Prompt 3: Subject Comparison
prompt_subject_comparison = f"""
**Function:** compare_subjects

The data below contains student grades in Math and Physics for 40 students.
Please compare the performance in Math and Physics:
1. In which subject did students perform better on average?
2. Which subject had more students scoring 80 or above?
3. In which subject was the lowest grade recorded?
4. What is the difference between the highest Math grade and the highest Physics grade?

Data: {data}
"""
output = llm.invoke(prompt_subject_comparison)
print(output)

I can help you with that!

**1. In which subject did students perform better on average?**

To find the average grade for each subject, we need to calculate the sum of grades and then divide by the total number of students (40).

Math: Sum = 3333, Average = 83.325
Physics: Sum = 3231, Average = 80.775

Since 83.325 is greater than 80.775, students performed better on average in Math.

**2. Which subject had more students scoring 80 or above?**

Let's count the number of students who scored 80 or above in each subject:

Math: 26 students
Physics: 24 students

Since 26 is greater than 24, more students scored 80 or above in Math.

**3. In which subject was the lowest grade recorded?**

The lowest grade recorded in Math is 51, and in Physics it's 43.

So, the lowest grade was recorded in Physics (43).

**4. What is the difference between the highest Math grade and the highest Physics grade?**

The highest Math grade is 98, and the highest Physics grade is 97.

The difference between these two grades is: 98 - 97 = 1

So, there is a 1-point difference between the highest Math grade and the highest Physics grade.

In [53]:
# Prompt 4: Identifying Top Performers
prompt_top_performers = f"""
**Function:** identify_top_performers

The data below contains student grades in Math and Physics for 40 students.
Please identify the top performers:
1. How many students scored 90 or above in both subjects?
2. What is the average Math grade for students who scored 90 or above in Physics?
3. What is the average Physics grade for students who scored 90 or above in Math?
4. How many students have a combined grade (Math + Physics) of 180 or higher?

Data: {data}
"""
output = llm.invoke(prompt_top_performers)
print(output)

I can help you identify the top performers based on the provided data. Here are the answers to your questions:

1. How many students scored 90 or above in both subjects?

After examining the data, I found that only 2 students scored 90 or above in both Math and Physics.

2. What is the average Math grade for students who scored 90 or above in Physics?

The students who scored 90 or above in Physics are: 98, 94, 96, 91, and 97. The average Math grade for these students is (88 + 89 + 93 + 77 + 65) / 5 = 84.4.

3. What is the average Physics grade for students who scored 90 or above in Math?

The students who scored 90 or above in Math are: 92, 89, 98, 93, and 96. The average Physics grade for these students is (88 + 85 + 94 + 90 + 72) / 5 = 86.2.

4. How many students have a combined grade (Math + Physics) of 180 or higher?

After calculating the combined grades, I found that 6 students have a combined grade of 180 or higher: 98 + 84 = 182; 94 + 90 = 184; 96 + 92 = 188; 91 + 97 = 188; 93 + 96 = 189; and 89 + 98 = 187.